# Generated by Django 6.0.6 on 2026-06-29 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Buses',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('route_long_name', models.CharField(max_length=255)),
                ('continuous_pickup', models.IntegerField(default=0)),
                ('continuous_drop_off', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=255)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('IN_TRANSIT', 'In Transit'), ('ARRIVING', 'Arriving'), ('AT_STOP', 'At Stop')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.bus')),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_sequence', models.IntegerField()),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.stop')),
            ],
            options={
                'ordering': ['stop_sequence'],
            },
        ),
        migrations.AddField(
            model_name='bus',
            name='current_stop_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.stoptime'),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('trip_headsign', models.CharField(max_length=255)),
                ('direction_id', models.IntegerField()),
                ('shape_id', models.CharField(max_length=100)),
                ('service_id', models.CharField(max_length=100)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.route')),
            ],
        ),
        migrations.AddField(
            model_name='stoptime',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.trip'),
        ),
        migrations.AddField(
            model_name='bus',
            name='current_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.trip'),
        ),
        migrations.CreateModel(
            name='WaitingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('ON_BOARD', 'On Board'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('COMPLETED', 'Completed')], default='WAITING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_requests', to='tracking.passenger')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_requests', to='tracking.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_requests', to='tracking.stop')),
            ],
        ),
        migrations.AddConstraint(
            model_name='stoptime',
            constraint=models.UniqueConstraint(fields=('trip', 'stop_sequence'), name='unique_stop_sequence_per_trip'),
        ),
    ]
