# Generated by Django 6.0.4 on 2026-06-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(default='BUS000', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
