# Generated by Django 6.0.6 on 2026-07-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='status',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('IN_TRANSIT', 'In Transit'), ('AT_STOP', 'At Stop')], default='IDLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='bus',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.CharField(max_length=100)),
                ('shape_pt_lat', models.FloatField()),
                ('shape_pt_lon', models.FloatField()),
                ('shape_pt_sequence', models.IntegerField()),
            ],
            options={
                'ordering': ['shape_pt_sequence'],
                'constraints': [models.UniqueConstraint(fields=('shape_id', 'shape_pt_sequence'), name='unique_shape_point')],
            },
        ),
        migrations.DeleteModel(
            name='BusLocation',
        ),
    ]
