# Generated by Django 6.0.6 on 2026-09-15 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_bus_status_alter_bus_is_active_shape_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingrequest',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiting_requests', to='tracking.trip'),
        ),
    ]
