# Generated by Django 6.0.4 on 2026-06-07 23:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_bus_bus_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stop',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='last_updated',
            new_name='last_update',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='current_stop_index',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='name',
        ),
        migrations.AddField(
            model_name='bus',
            name='capacity',
            field=models.IntegerField(default=65),
        ),
        migrations.AddField(
            model_name='bus',
            name='occupied_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passenger',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='current_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='passenger',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='path',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='current_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bus',
            name='current_lng',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='tracking.route'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stop',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='tracking.route'),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lng', models.FloatField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('assigned', 'Assigned'), ('en_route', 'En Route'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='tracking.bus')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='tracking.passenger')),
            ],
        ),
        migrations.DeleteModel(
            name='BusLocation',
        ),
    ]
