# Generated by Django 6.0.6 on 2026-09-15 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_waitingrequest_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitingrequest',
            name='route',
        ),
    ]
