# Generated by Django 6.0.6 on 2026-09-15 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_remove_waitingrequest_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitingrequest',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_requests', to='tracking.trip'),
        ),
    ]
