# Generated by Django 6.0.7 on 2026-07-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='capacity',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='bus',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='route',
            name='origin',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
