# Generated by Django 6.0.7 on 2026-09-07 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_bus_capacity_bus_registration_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_requests', to='tracking.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_requests', to='tracking.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_requests', to='tracking.route')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('driver', 'route'), name='uniq_pending_route_request_per_driver_route')],
            },
        ),
    ]
