# Generated by Django 6.1.1 on 2026-09-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_busroute_busmovement_triptracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='direction',
            field=models.CharField(default='forward', max_length=10),
        ),
        migrations.AddField(
            model_name='bus',
            name='route_progress',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bus',
            name='scheduled_stops',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='route',
            name='distance_km',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='estimated_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='route',
            name='waypoints',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='stop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
