# Generated by Django 6.0.7 on 2026-09-07 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_routerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='current_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bus',
            name='current_lng',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.route'),
        ),
    ]
