# Generated by Django 6.1.1 on 2026-09-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_bus_direction_bus_route_progress_bus_scheduled_stops_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusRoute',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='route',
            name='path',
            field=models.JSONField(default=list),
        ),
    ]
