# Generated by Django 6.0.6 on 2026-09-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_driver_driverbusassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='name',
        ),
    ]
